# -*- coding: utf-8 -*-
"""TP N° 9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KANuRm9ji6T5g6QLDIfh-QY_jGzS4x2e

* Ej N° 1
"""

import sqlite3 as sql
class Conexion_BD():
  def __init__(self, bd):
    self.conexion = sql.connect(bd)
    self.cursor = self.conexion.cursor()

  def consulta(self, consulta):
    self.cursor.execute(consulta)
    
  def commit(self):
    self.conexion.commit()

  def cerrar(self):
    self.conexion.close()

conexion = Conexion_BD("Productos_db.sqlite")
conexion.consulta("""CREATE TABLE Productos(id_producto INTEGER PRIMARY KEY AUTOINCREMENT,
                                         nombre_producto TEXT,
                                         cantidad_producto INTEGER,
                                         precio_productos INTEGER,
                                         categoria_producto TEXT)""")
                                        
conexion.commit()
conexion.cerrar()

"""* Ej N° 2"""

conexion = Conexion_BD('Productos_db.sqlite')
conexion.consulta('INSERT INTO Productos VALUES(NULL, "borrador", 0, 5, "libreria")')
conexion.commit()

conexion = Conexion_BD('Productos_db.sqlite')
conexion.consulta('SELECT * FROM Productos ORDER BY id_producto ASC')
lista_producto = conexion.cursor.fetchall()
conexion.commit()
print("LISTA DE PRODUCTOS")
print("NRO \t Codigo \t Nombre \t Cantidad \t Precio \t Categoria")
print("*" * 85)
i = 1
for item in lista_producto:
  if item[0] == 1:
     print(f"{i}\t {item[0]} \t {item[1]} \t\t {item[2]} \t\t  {item[3]} \t\t {item[4]}")
  else:
     print(f"{i}\t {item[0]} \t {item[1]} \t\t {item[2]} \t\t {item[3]} \t\t {item[4]}")
  i += 1

print("*"* 85)
conexion.consulta("SELECT nombre_producto FROM Productos WHERE cantidad_producto = 0")
lista_producto = conexion.cursor.fetchall()
conexion.commit()
print("LISTA DE PRODUCTOS SIN STOCK")
print("NRO \t Nombre")
i += 1
for item in lista_producto:
  print(f"{i} \t {item[0]}")
  i += 1

conexion = Conexion_BD('Productos_db.sqlite')
nombre = 'top rosa'
cantidad = 8
conexion.consulta =(f'UPDATE Productos SET nombre_producto= "{nombre}", cantidad_producto= {cantidad} WHERE nombre_producto="buzorosa"')
conexion.commit()

codigo = 5
conexion.consulta(f"DELETE FROM Productos WHERE id_producto={codigo}")
conexion.commit()
conexion.cerrar()